//! Numerical parity against onnxruntime references.

use fluidvad::{segment_speech, ModelState, SileroModel, VadSegmentationConfig, FRAME_SIZE};

/// Committed reference: one 576-sample input (zero context + 512 samples) and
/// its expected probability, generated by scripts/prepare_model.py from the
/// unmodified upstream model under ORT.
#[test]
fn single_frame_parity_with_ort_reference() {
    let txt = include_str!("../models/parity_ref.txt");
    let mut lines = txt.lines();
    let x: Vec<f32> = lines
        .next()
        .unwrap()
        .split_whitespace()
        .map(|s| s.parse().unwrap())
        .collect();
    let expected: f32 = lines.next().unwrap().trim().parse().unwrap();
    assert_eq!(x.len(), 576);
    assert!(
        x[..64].iter().all(|&v| v == 0.0),
        "reference context must be zeros"
    );

    // A fresh ModelState has a zero context, matching the reference exactly.
    let model = SileroModel::new().expect("model");
    let (prob, _) = model
        .process_frame(&x[64..], &ModelState::initial())
        .expect("frame");
    assert!(
        (prob - expected).abs() < 1e-5,
        "tract={prob} ort={expected}"
    );
}

/// Full-clip parity on real speech: per-frame probabilities vs ORT running the
/// same fixed model (testdata generated by scripts; skipped if absent).
#[test]
fn real_audio_frame_probabilities_match_ort() {
    let wav_path = concat!(env!("CARGO_MANIFEST_DIR"), "/testdata/speech_16k.wav");
    let ref_path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/testdata/speech_16k_ort_probs.txt"
    );
    let (Ok(mut reader), Ok(ref_txt)) = (
        hound::WavReader::open(wav_path),
        std::fs::read_to_string(ref_path),
    ) else {
        eprintln!("SKIP: testdata not present");
        return;
    };
    let samples: Vec<f32> = reader
        .samples::<i16>()
        .map(|s| s.unwrap() as f32 / 32768.0)
        .collect();
    let expected: Vec<f32> = ref_txt.lines().map(|l| l.trim().parse().unwrap()).collect();

    let model = SileroModel::new().expect("model");
    let probs = model.probabilities(&samples).expect("probabilities");
    assert_eq!(probs.len(), expected.len());

    let max_diff = probs
        .iter()
        .zip(&expected)
        .map(|(a, b)| (a - b).abs())
        .fold(0.0f32, f32::max);
    assert!(max_diff < 1e-4, "max per-frame diff vs ORT: {max_diff}");
    println!("frames: {}, max diff vs ORT: {max_diff:e}", probs.len());
}

/// End-to-end segmentation smoke test on real speech.
#[test]
fn segments_real_speech_sensibly() {
    let wav_path = concat!(env!("CARGO_MANIFEST_DIR"), "/testdata/speech_16k.wav");
    let Ok(mut reader) = hound::WavReader::open(wav_path) else {
        eprintln!("SKIP: testdata not present");
        return;
    };
    let samples: Vec<f32> = reader
        .samples::<i16>()
        .map(|s| s.unwrap() as f32 / 32768.0)
        .collect();
    let duration = samples.len() as f64 / 16000.0;

    let model = SileroModel::new().expect("model");
    let start = std::time::Instant::now();
    let segments =
        segment_speech(&model, &samples, &VadSegmentationConfig::default()).expect("segment");
    let elapsed = start.elapsed().as_secs_f64();

    assert!(!segments.is_empty(), "real speech must yield segments");
    let speech: f64 = segments.iter().map(|s| s.duration()).sum();
    assert!(
        speech > 0.5 * duration,
        "clip is mostly speech; got {speech:.2}s of {duration:.2}s"
    );
    for seg in &segments {
        assert!(seg.start_time >= 0.0 && seg.end_time <= duration + 1e-9);
        assert!(seg.duration() > 0.0);
    }
    println!(
        "segments: {segments:?}\nspeech {speech:.2}s / {duration:.2}s, RTFx {:.0}x",
        duration / elapsed
    );
    let _ = FRAME_SIZE;
}
